# Site settings
description: 'retromatter by junl.ee - Archival Portal for Digital Preservation and Retrocomputing Projects.' # Updated description
baseurl: "" # The subpath of your site, e.g. /blog
url: "https://junl.ee" # The base hostname & protocol for your site

# SEO/Metadata Configuration
title: "→ジュンリー | Digital Archive & Projects"
author:
  name: "Junlee"
  email: "junl.ee@gmail.com"
logo: "/favicon.ico"
social:
  name: "Retromatter"
  links:
    - "https://github.com/retromatter"
    - "https://twitter.com/retromatter"
    - "https://linkedin.com/in/junlee" # Placeholder, adjust if needed

# Build settings
plugins:
  - jekyll-feed
  - jekyll-seo-tag # Added for better metadata generation

# Exclude files from the build process
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/
